#Numpy Operations

In [18]:
import numpy as np
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype=float)
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]], dtype=float)

In [19]:
#1.Create a 3×4 array filled with zeros.
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
#2.Create a 2×3×4 array filled with ones of datatype int16.
np.ones((2,3,4),dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [21]:
#Generate values from 10 to 25 (exclusive) with step 5
np.arange(10,25,5)

array([10, 15, 20])

In [23]:
#4. Generate 9 evenly spaced values between 0 and 2.
e=np.linspace(0,2,9)
e

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [24]:
#5.Create a 2×2 constant array where every value is 7.
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [31]:
#Create a 2×2 identity matrix and a 2×2 random matrix, then print both.
x=np.eye(2)
y=np.random.random((2,2))
print(x,"\n",y)


[[1. 0.]
 [0. 1.]] 
 [[0.67908915 0.32432835]
 [0.6210502  0.76223717]]


In [35]:
#For a, b, and c: print shape, ndim, and size.
np.shape(a)

(3,)

In [33]:
np.shape(b)

(2, 3)

In [34]:
np.shape(c)

(2, 2, 3)

In [36]:
np.ndim(a)

1

In [37]:
np.ndim(b)

2

In [38]:
np.ndim(c)

3

In [39]:
np.size(a)

3

In [40]:
np.size(b)

6

In [41]:
np.size(c)

12

In [43]:
print(a.dtype)
print(b.dtype)
print(c.dtype)

int64
float64
float64


In [44]:
print(a.dtype.name)
print(b.dtype.name)
print(c.dtype.name)

int64
float64
float64


In [45]:
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
x=np.multiply(b,b)
x

array([[ 2.25,  4.  ,  9.  ],
       [16.  , 25.  , 36.  ]])

In [47]:
np.divide(b,b)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [48]:
np.add(a,b)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [49]:
np.subtract(a,b)

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [50]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [51]:
np.sqrt(b)

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [52]:
np.sqrt(c)

array([[[1.22474487, 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974]],

       [[1.73205081, 1.41421356, 1.        ],
        [2.        , 2.23606798, 2.44948974]]])

In [53]:
np.add(a,b)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [54]:

np.min(a)

np.int64(1)

In [55]:
np.max(a)

np.int64(3)

In [56]:
np.cumsum(a)

array([1, 3, 6])

In [57]:
np.mean(a)

np.float64(2.0)

In [58]:
np.median(a)

np.float64(2.0)

In [59]:
np.std(a)

np.float64(0.816496580927726)